# Generated by Django 4.0.5 on 2022-07-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="First_name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "myfirstname",
                    models.CharField(
                        default="Shaun",
                        max_length=20,
                        verbose_name="first name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Last_name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mylastname",
                    models.CharField(
                        default="Friend",
                        max_length=20,
                        verbose_name="last name",
                    ),
                ),
            ],
        ),
    ]
