# Generated by Django 4.0.5 on 2022-07-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0002_rename_first_name_firstname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firstname',
        ),
        migrations.DeleteModel(
            name='Lastname',
        ),
    ]
