# Generated by Django 4.0.5 on 2022-07-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mypages', '0003_delete_firstname_delete_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='favegames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=100, verbose_name='name of game/series')),
                ('startyear', models.DateField(verbose_name='release year/start of series')),
            ],
        ),
    ]
