# Generated by Django 4.0.5 on 2022-07-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0006_mods_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mods',
            new_name='modslist',
        ),
    ]
